### ISSUE TITLE
How to show and move to the first item

### ISSUE THREAD

**Issue by hoang23391** [kHRYSTAL/CircleRecyclerView#11]
![image](https://user-images.githubusercontent.com/25897875/27682463-d1259050-5cec-11e7-9d25-c7295cd6fd1f.png)
Hello, i used ScaleYMode, i want to set height for item and recyclerview =100dp, my aim was show only one item.
When i opened the app, the recyclerview show the item in position 3 instead of 0.
How to show the item 0 first? Please help me, and thanks for reading

**Comment by hoang23391** [comment]
if u could, please also help me How to get Data of the item which was display on the screen without click on the item? thank you.

**Comment by hoang23391** [comment]
and if i create a Button, how i should do if i want to clicked on the button, the item number will change from current possition to next position? i tried to used scrolltoposition but that not work.

**Comment by kHRYSTAL** [comment]
i commit branch #11 to show effect, and suggest you can use [RecyclerViewPager](https://github.com/lsjwzh/RecyclerViewPager), because this library is hard find current position
