### ISSUE TITLE
水平那个圆弧

### ISSUE THREAD

**Issue by meihuali** [kHRYSTAL/CircleRecyclerView#14]
今天老板让我们做一个水平可以滑动的圆弧找了很久才找到作者的这个裤，然而我下载了看了下非常棒，
，然而公司要求 是 圆弧朝上不是朝下，然而自己不太会修改·所以联系到了作者的 QQ 作者人很好·然后说晚上下班了·加一个上去····

**Comment by kHRYSTAL** [comment]
新增 `CircularHorizontalModeBTT` 
注意: item的布局文件在根布局设置`marginTop`, `alginParentBottom=true`是无效的, 
因此参数增加了偏移量配置, 这个参数是指显示时最中间的item相对于`RecyclerView`顶部的距离
可根据需要自行控制
第二个参数是指是否需要其他item旋转
