### ISSUE TITLE
RecycleView设置监听后，当点击RecycleView内部的控件后，内部控件为什么会往上漂移， 这是为什么？

### ISSUE THREAD

**Issue by linarykai** [kHRYSTAL/CircleRecyclerView#16]
昨天已经用到了项目中，很好已用上，多谢！
不过现在有个问题，需要请教下，设置监听后，当点击RecycleView内部的item控件后，内部控件为什么会往上漂移？
大神 盼答复！

**Comment by kHRYSTAL** [comment]
@linarykai 你好 `CircleRecyclerView` 并没有修改手势操作的处理
因此可能有以下情况导致
* 需要你查看你的项目控件是否重写了`dispatchTouchEvent` 以及 `onTouchEvent`的实现 如果有建议打上log查看是否触发了`CircleRecyclerView`的操作 如果触发, 可以在`dispatchTouchEvent`中 加上
`circleRecyclerView.requestDisallowTouchEvent(true)`

* 查看这个library中你实现的`ItemViewMode` 在你点击项目控件时 是否触发了applyView 导致ItemView触发了变形而看起来像控件向上移动

**Comment by linarykai** [comment]
大神 能不能加下联系方式 我请教你下问题，弄了好久了，一直弄不好

**Comment by linarykai** [comment]
我是在Adapter里面加对item项的holder.itemView的监听回调以及加了选中项目的item状态改变，就会把里面的内容往上漂移了。


//选中item时，改变状态
        if (position == selected) {
            holder.fl_recycle.setBackgroundResource(R.drawable.effect_item_selected_bg);
          holder.tv_item_makeup.setTextColor(GlobalConfig.context.getResources().getColor(R.color.take_camera));
        } else {
            holder.fl_recycle.setBackgroundResource(0);
      holder.tv_item_makeup.setTextColor(GlobalConfig.context.getResources().getColor(R.color.white));
        }

**Comment by kHRYSTAL** [comment]
主分支已合并
