### ISSUE TITLE
auto scroll when open app wehn rtl app

### ISSUE THREAD

**Issue by hossein-rezaeian** [kHRYSTAL/CircleRecyclerView#18]
hi
i am set  android:supportsRtl="false" and   tools:replace="android:supportsRtl" in file manifest And when the app opens The recyclerview automatically scrool be and goes to another item And the other does not work properly 
what should I do i need to  android:supportsRtl="false" and   tools:replace="android:supportsRtl" my project

**Comment by kHRYSTAL** [comment]
thanks reply, the recyclerView automatically scroll to another item is not cause by set `android:supportsRtl="false"`, this key-value not effect this library, 
and it is cause by field `mNeedCenterForce` in `CircleRecycleView.java`, you can use 
```
circleRecycleView.setNeedCenterForce(false);
```
when init

and use
```
circleRecycleView.setNeedCenterForce(true);
circleRecycleView.requestLayout();
```
when you need the the shortest distance of center item scroll to center
