### ISSUE TITLE
RotateXScaleYViewMode的DEMO滑动时，整个列表在闪烁

### ISSUE THREAD

**Issue by ShaunWilson** [kHRYSTAL/CircleRecyclerView#19]
RT,RotateXScaleYViewMode的DEMO滑动时，整个列表都在闪烁

**Comment by kHRYSTAL** [comment]
@ShaunWilson 感谢回复 因为demo是运行在240dpi模拟器上的 在ViewMode中偏移/倾斜/缩放我写的都是固定值, 在使用到实际项目中需要进行适配操作
