### ISSUE TITLE
Contineous Scrolling

### ISSUE THREAD

**Issue by milaptank** [kHRYSTAL/CircleRecyclerView#2]
Hello @kHRYSTAL thanks for this library 
I am use in my project some of customization i have done but is there any changes to auto scrolling smoothing 
i have tried but its scrolling step by step not smoothing  and RV method smooth scroll not working as per name

**Comment by kHRYSTAL** [comment]
@milaptank 
this library method `smoothScrollToView(View v)` just support smooth scroll center which itemView can visible on screen, and if the itemView beyond screen, you can use `scrollToPosition(int)`

also you can `compile 'com.android.support:recyclerview-v7:23.4.0'`, use `LinearSnapHelper` instead this library if you needn't loop and you can implements custom effects 
Thanks for reply :-)

**Comment by milaptank** [comment]
Hello @kHRYSTAL i have tried as you have ask to do but still not getting smooth scroll any luck from your side?

**Comment by kHRYSTAL** [comment]
hi @milaptank
pls show me the code some of your customization. thank you

**Comment by milaptank** [comment]
Hey many many thanks finally I got solution with the help of your  Repo [MarqueeRecyclerView](https://github.com/kHRYSTAL/MarqueeRecyclerView)  
I have merge your two library [CircleRecyclerView](https://github.com/kHRYSTAL/CircleRecyclerView) + [MarqueeRecyclerView](https://github.com/kHRYSTAL/MarqueeRecyclerView)) = Infinite scrolling Recyclerview  Thank you
