### ISSUE TITLE
Item view in not horizontal center

### ISSUE THREAD

**Issue by twolight** [kHRYSTAL/CircleRecyclerView#3]
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:layout_width="100dp"
    android:layout_height="100dp"
    android:background="@color/colorPrimaryDark">
    <ImageView
        android:id="@+id/item_img"
        android:layout_gravity="center_horizontal"
        android:layout_width="48dp"
        android:layout_height="48dp" />
    <TextView
        android:id="@+id/item_text"
        android:layout_gravity="center_horizontal"
        android:layout_width="wrap_content"
        android:layout_height="match_parent" />
</LinearLayout>

In item_h.xml ,if android:layout_width="80dp" change to android:layout_width="100dp"， Then The item view is not horizontal center

**Comment by twolight** [comment]
![image](https://cloud.githubusercontent.com/assets/5369941/19560177/f45a2570-9705-11e6-8157-2e47bdabc273.png)
Like this.Please fix.

**Comment by twolight** [comment]
And can you remove the padding between items

**Comment by kHRYSTAL** [comment]
@twolight 
thx reply
I find this issue because `scrollToPosition(DEFAULT_SELECTION)` not work when onlayout at first time in real phone
add code fix find center in loop:

```
+ private Handler mPostHandler = new Handler(){
+        @Override
+        public void handleMessage(Message msg) {
+            scrollToPosition(DEFAULT_SELECTION);
+        }
+    };
```

```
 if (mNeedLoop) {
//            scrollToPosition Notwork use delay
+            if (!mFirstOnLayout) {
+                mFirstOnLayout = true;
+                mPostHandler.sendEmptyMessage(0);
+            }
-            scrollToPosition(DEFAULT_SELECTION);
            mCurrentCenterChildView = findViewAtCenter();
            smoothScrollToView(mCurrentCenterChildView);
        }
```

![](http://ww4.sinaimg.cn/large/65e4f1e6gw1f8z8l1pd5fg20cz0l9780.gif)

and padding because item need scale , couldn't remove

**Comment by twolight** [comment]
Nice!
