### ISSUE TITLE
App was crashing, if I'm using androidX.

### ISSUE THREAD

**Issue by appcarevenkataramana** [kHRYSTAL/CircleRecyclerView#30]
java.lang.NullPointerException: Attempt to read from field 'android.view.View androidx.recyclerview.widget.RecyclerView$ViewHolder.itemView' on a null object reference

issue at Override method-> onLayout()

**Comment by kHRYSTAL** [comment]
feat[androidX]: [add androidx branch](https://github.com/kHRYSTAL/CircleRecyclerView/tree/androidx)
