### ISSUE TITLE
Make the view as full circle 

### ISSUE THREAD

**Issue by ahmedsalemelzeiny** [kHRYSTAL/CircleRecyclerView#32]
Hi @kHRYSTAL

Thank you for your effort and sharing this code, I need to know if there is any way that I can use the view as full circle instead of half circle in HORIZONTAL_CIRCL mode.

How I can achieve that?

**Comment by kHRYSTAL** [comment]
Hi @ahmedsalemelzeiny , RecyclerView cannot make full circle effort, if you need full circle UI you can make custom view like this
[https://github.com/hongyangAndroid/Android-CircleMenu](https://github.com/hongyangAndroid/Android-CircleMenu)
[doc/blog: https://blog.csdn.net/lmj623565791/article/details/43131133](https://blog.csdn.net/lmj623565791/article/details/43131133)
