### ISSUE TITLE
无限循环取最大值，万一真的滑到第一个呢？

### ISSUE THREAD

**Issue by W-quan** [kHRYSTAL/CircleRecyclerView#4]
这个有没有处理？
或许可以参考这个http://blog.csdn.net/laibaigan/article/details/8863627

**Comment by cheng7692019** [comment]
点击任意view的事件真难加，加了没效果，要不这控件真没用的

**Comment by kHRYSTAL** [comment]
感谢回复，近期比较忙，抱歉比较晚回复，由于设置max value后最大值左右滑动item 超过10亿个
可以理解成无限 
通过链接的办法会造成数据冗余 ，同时无限条目与寻找中间值是互斥事件
之前测试了另一种办法 但是也不是很好
可以参考[链接](http://www.akexorcist.com/2012/08/android-code-list-view-endless.html)

**Comment by aloe20** [comment]
你好，我看了一下CircularViewMode的源码，item的移动轨迹是余弦运动，如何做到真正以圆的轨迹运动呢？
