### ISSUE TITLE
CircularViewMode的轨迹为余弦。真正以圆的轨迹或圆弧的轨迹运动，该如何实现？

### ISSUE THREAD

**Issue by aloe20** [kHRYSTAL/CircleRecyclerView#9]
你好，我看了一下CircularViewMode的源码，item的移动轨迹是余弦运动，如何做到真正以圆的轨迹运动呢？

**Comment by kHRYSTAL** [comment]
@aloe20 因为本身线性列表 真正的圆轨迹会造成重叠 如果需要圆轨迹运动可以参照hongyang的csdn建行菜单那篇blog 感谢回复

**Comment by aloe20** [comment]
类似建行菜单也看过，是继承ViewGroup，在里面添加View。若要添加20个View,50个View，那种实现就不现实了。若用RecyclerView实现一个四分之一圆弧就很好了

**Comment by kHRYSTAL** [comment]
如果时圆弧形的屏幕外子view需要回收 可以换一种机制,就是ViewGroup内只有可见的几个子view, 滑动的时候updateItem就可以 这周有时间的话 我尝试做一下 感谢提供思路

**Comment by aloe20** [comment]
用RecyclerView实现90度圆弧菜单，做了几天，一直有bug，正在解决中。希望你做出来后，分享分享经验。

**Comment by wangdaliu** [comment]
@aloe20 正好要做这个效果（圆形轨迹），有没有类似的库推荐的

**Comment by aloe20** [comment]
@wangdaliu 不好意思，一直没注意看消息。可以看一下这篇文章，有问题直接简书上@我 https://www.jianshu.com/p/7d020f8797fa
